language: node_js

node_js:
  - "10"

matrix:
  include:
    - os: osx
      osx_image: xcode9.4

    - os: linux

cache:
  yarn: true

script:
  - yarn run preelectron-pack
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn run electron-pack-macos ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn run electron-pack-linux ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn run electron-pack-win ; fi