language: node_js

node_js:
  - "10"

matrix:
  include:
    - os: osx
      osx_image: xcode9.4

    - os: linux
      services: docker
      language: generic

cache:
  yarn: true

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash scripts/build-osx.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash scripts/build-linux.sh ; fi